name: Stock Alert Bot

on:
  schedule:
    - cron: "30 12 * * *"   # runs daily (6 PM IST)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pandas yfinance

      - name: Run scripts
        run: |
          python stocks.py
          python main.py
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}

      - name: Commit results
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add latest_results.csv
          git commit -m "update results" || echo "no changes"
          git push
